### ISSUE TITLE
0.4.1 release is broken?

### ISSUE THREAD

**Issue by SamJust** [demike/TsUML2#11]
On version 0.4.1 /dist folder is missing, while still being referenced in package.json.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/24614472/167204508-b9d9219c-52d3-4e23-8304-2e5036e9d1bd.png">
If I downgrade to 0.4.0 it magically appears.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/24614472/167204634-6a52a507-8164-4ad8-a48b-a85f8099a8c6.png">

**Comment by demike** [comment]
Hi I released a fix: 0.4.2
Sorry for the inconvenience, I have to invest some time into github actions
