### ISSUE TITLE
Add documentation to generate programmatically .

### ISSUE THREAD

**Issue by lokeshdaiya** [demike/TsUML2#14]
This library is `npm` package and has capability to use in other node applications.

There should be documentation how this can be used in NodeJS programs 

Example:

```
const {createNomnomlSVG} = require('tsuml2')

createNomnomlSVG({glob: `./src/app/**/!(*.d|*.spec).ts`,outFile: 'd:/apps/src/demo.svg'});
```

**Comment by demike** [comment]
fixed in #15
