### ISSUE TITLE
Does not work with export default class

### ISSUE THREAD

**Issue by stared** [demike/TsUML2#20]
First, thank you @demike for developing this nice and useful project! :)

However, it does not work well with `export default class`. That is:

* names are erased (set to "default")
* if there is more than one default export, they overshadow each other.

I prepared a minimal example, https://github.com/stared/tsuml2-default-export-error-example (commit [7e2a479](https://github.com/stared/tsuml2-default-export-error-example/tree/7e2a479492b59dd6cd2539d1e19de83485776762/src) for the version resulting in an error):

```typescript
import Person from './person'
import { Vector, Color } from './structures'

export default class MainClass {
  constructor(public color: Color, public v: Vector, public person: Person) {}
}
```

```typescript
export default class Person {
  constructor(public name: string, public surname: string) {}
}
```

```typescript
export interface Vector {
  x: number
  y: number
}

export interface Color {
  r: number
  g: number
  b: number
}
```

I run `tsuml2 --glob "./src/**/*.ts" -m` and get:

<img width="307" alt="Screenshot 2023-02-15 at 12 55 28" src="https://user-images.githubusercontent.com/1001610/219022153-5400c774-9c11-462b-b463-bff6e9bfbb9d.png">

Changing to non-default export makes it work (https://github.com/stared/tsuml2-default-export-error-example/commit/c9d15ec0fb16ce2dbd0f3f4e419c1b54ed905952):

<img width="480" alt="Screenshot 2023-02-15 at 12 59 56" src="https://user-images.githubusercontent.com/1001610/219022090-08be488e-66ce-4469-9064-5707d2677092.png">

My project has plenty of default exports. To create a diagram I need to manually change them not non-default exports (and consequently, non-default imports). 

Is there a way to make it work?

**Comment by demike** [comment]
Thanks for the great explanation. Will take a look at it.

**Comment by demike** [comment]
@stared can you give the new version (0.9) a try.
Tested default exports of interfaces and classes + inheritance , but maybe I missed some cases.

**Comment by stared** [comment]
Thanks!

It works, but almost. See that `person` is of the type `default`.

<img width="489" alt="Screenshot 2023-02-16 at 14 42 40" src="https://user-images.githubusercontent.com/1001610/219380942-29a6c936-fa1e-4edc-8699-63ba40d3ebeb.png">

**Comment by demike** [comment]
Ahhh forgot the members ... Will do that

**Comment by demike** [comment]
@stared the new version 0.10.0 should support members of  "default export type"

**Comment by stared** [comment]
Works like a charm - thank you!
<img width="467" alt="Screenshot 2023-02-16 at 16 35 36" src="https://user-images.githubusercontent.com/1001610/219413322-21af8bbb-0fa1-4882-a1f7-679997f7d361.png">
