### ISSUE TITLE
Line ending conflicts on MacOS

### ISSUE THREAD

**Issue by SamJust** [demike/TsUML2#8]
I've installed 0.2.0 version of the package. I'm also running macOS Catalina 10.15.7 (19H524).
The issues i'm getting is
```
env: node\r: No such file or directory
```
As far as I know, it' related to line endings.
Will there be a fix or what is workaround?

**Comment by demike** [comment]
I can take a look. It's time to release a new version anyhow.

Viktor Bezrodnyi ***@***.***> schrieb am Fr., 8. Apr. 2022,
17:58:

**Comment by demike** [comment]
@SamJust tsuml2 0.3.0 should fix your line ending problems

**Comment by SamJust** [comment]
@demike I'm still getting the exact same error. I will try to investigate further, maybe it's something on my part.
