### ISSUE TITLE
Different `typescript` module from dependency of your dependency uncompatible with original `typescript`

### ISSUE THREAD

**Issue by phpcoder2022** [demike/TsUML2#84]
Versions:

- tsuml2: 0.16.1
- ts-morph: 19.0.0
- @ts-morph/common: 0.20.0

**To Reproduce**

1. Parse any typescript class contains properties with modifier.
2. Call `getCombinedModifierFlags(node)` from you typescript file and original typescript module.
3. See that results are different.

**Expected behavior**

Its are equal.

Author of `ts-morph`s [responsed me](https://github.com/dsherret/ts-morph/issues/1534) that this error is your.

**Comment by demike** [comment]
@phpcoder2022 could you provide a minimal reproduction for the faulty behaviour?

**Comment by phpcoder2022** [comment]
I created [repo](https://github.com/phpcoder2022/tsuml2-bug) for this

**Comment by demike** [comment]
@phpcoder2022  I really did an import of ModifierFlags directly from "typescript". 
@dsherret thanks for the clarification. I will switch to the version of ts-morph to completely remove the runtime dependency
on typescript.

**Comment by demike** [comment]
@phpcoder2022 should be fixed 0.17.0

**Comment by phpcoder2022** [comment]
Thanks. This case works fine.
